/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cw2.t1;

import java.sql.*;
import java.util.Locale;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author ASUS
 */
public class dashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashboard
     */
    
    static int l,m,s;
    
    public dashboard() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        createchart();
    }

    public void getvaluesdb(){
        try {
            String url = AppConfig.dbUrl();
            String uname = AppConfig.dbUser();
            String pass = AppConfig.dbPassword();
            String query = "SELECT * FROM warehouse_req WHERE nic = '"+Interface1.keynic+"'";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, uname, pass);
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);

            if(rs.next()){
                l = rs.getInt("crates_l");
                m = rs.getInt("crates_m");
                s = rs.getInt("crates_s");
            }
           st.close();
           connection.close();
           
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
    }
    
    public void createchart(){
        lblwel.setText("Welcome , "+SorL.username);
        getvaluesdb();
        int free = 100-(l+(m/2)+(s/4));
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Free space", new Integer(free));
        dataset.setValue("Large crates", new Integer(l));
        dataset.setValue("Medium crates", new Integer(m));
        dataset.setValue("Small crates", new Integer(s));
        JFreeChart chart = ChartFactory.createPieChart("", dataset, true, true, false);
        PiePlot p=(PiePlot)chart.getPlot();
        p.setDirection(Rotation.CLOCKWISE);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        pchart.add(chartPanel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pchart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblwel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        lblname1 = new javax.swing.JLabel();
        lblname2 = new javax.swing.JLabel();
        lblname3 = new javax.swing.JLabel();
        lblname4 = new javax.swing.JLabel();
        lblname5 = new javax.swing.JLabel();
        lblname6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(673, 572));

        pchart.setBackground(new java.awt.Color(255, 255, 255));
        pchart.setPreferredSize(new java.awt.Dimension(213, 213));
        pchart.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw2/t1/male_user_50px.png"))); // NOI18N

        lblwel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblwel.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 95, 79));

        lblname.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("Our");

        lblname1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblname1.setForeground(new java.awt.Color(255, 255, 255));
        lblname1.setText("Branches");

        lblname2.setFont(new java.awt.Font("Consolas", 2, 24)); // NOI18N
        lblname2.setForeground(new java.awt.Color(255, 255, 255));
        lblname2.setText("Kandy");

        lblname3.setFont(new java.awt.Font("Consolas", 2, 24)); // NOI18N
        lblname3.setForeground(new java.awt.Color(255, 255, 255));
        lblname3.setText("Colombo");

        lblname4.setFont(new java.awt.Font("Consolas", 2, 24)); // NOI18N
        lblname4.setForeground(new java.awt.Color(255, 255, 255));
        lblname4.setText("Matara");

        lblname5.setFont(new java.awt.Font("Consolas", 2, 24)); // NOI18N
        lblname5.setForeground(new java.awt.Color(255, 255, 255));
        lblname5.setText("Galle");

        lblname6.setFont(new java.awt.Font("Consolas", 2, 24)); // NOI18N
        lblname6.setForeground(new java.awt.Color(255, 255, 255));
        lblname6.setText("Jaffna");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblname2)
                        .addComponent(lblname3)
                        .addComponent(lblname4)
                        .addComponent(lblname5)
                        .addComponent(lblname6))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblname1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblname)
                .addGap(18, 18, 18)
                .addComponent(lblname1)
                .addGap(31, 31, 31)
                .addComponent(lblname2)
                .addGap(26, 26, 26)
                .addComponent(lblname3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lblname4)
                .addGap(31, 31, 31)
                .addComponent(lblname5)
                .addGap(33, 33, 33)
                .addComponent(lblname6)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblwel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(pchart, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblwel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pchart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblname1;
    private javax.swing.JLabel lblname2;
    private javax.swing.JLabel lblname3;
    private javax.swing.JLabel lblname4;
    private javax.swing.JLabel lblname5;
    private javax.swing.JLabel lblname6;
    private javax.swing.JLabel lblwel;
    private javax.swing.JPanel pchart;
    // End of variables declaration//GEN-END:variables
}
