/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cw2.t1;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;

/**
 *
 * @author ASUS
 */
public class Interface1 extends javax.swing.JFrame {

    /**
     * Creates new form Interface1
     */
    
    public static String keynic=null;
    
    public Interface1() {
        initComponents();
        getkey();
        dashboard dash = new dashboard();
        pchange.removeAll();
        pchange.add(dash).setVisible(true);
        dash.getContentPane().setBackground( Color.WHITE );            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblwms = new javax.swing.JLabel();
        pdash = new javax.swing.JPanel();
        lbldash = new javax.swing.JLabel();
        pmoving = new javax.swing.JPanel();
        lblmoving = new javax.swing.JLabel();
        padd = new javax.swing.JPanel();
        lbladd = new javax.swing.JLabel();
        pset = new javax.swing.JPanel();
        lblset = new javax.swing.JLabel();
        plogout = new javax.swing.JPanel();
        lbllogout = new javax.swing.JLabel();
        lblicon1 = new javax.swing.JLabel();
        lblback = new javax.swing.JLabel();
        pchange = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Warehouse Management System");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 95, 79));
        jPanel2.setPreferredSize(new java.awt.Dimension(348, 572));

        lblwms.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblwms.setForeground(new java.awt.Color(255, 255, 255));
        lblwms.setText("WMS");

        pdash.setBackground(new java.awt.Color(0, 95, 79));
        pdash.setPreferredSize(new java.awt.Dimension(347, 68));

        lbldash.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lbldash.setForeground(new java.awt.Color(255, 255, 255));
        lbldash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldash.setText("Dashboard");
        lbldash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldashMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pdashLayout = new javax.swing.GroupLayout(pdash);
        pdash.setLayout(pdashLayout);
        pdashLayout.setHorizontalGroup(
            pdashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbldash, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
        pdashLayout.setVerticalGroup(
            pdashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdashLayout.createSequentialGroup()
                .addComponent(lbldash, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pmoving.setBackground(new java.awt.Color(0, 95, 79));
        pmoving.setPreferredSize(new java.awt.Dimension(347, 68));

        lblmoving.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblmoving.setForeground(new java.awt.Color(255, 255, 255));
        lblmoving.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmoving.setText("Moving");
        lblmoving.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmovingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblmovingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblmovingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pmovingLayout = new javax.swing.GroupLayout(pmoving);
        pmoving.setLayout(pmovingLayout);
        pmovingLayout.setHorizontalGroup(
            pmovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmoving, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
        pmovingLayout.setVerticalGroup(
            pmovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmovingLayout.createSequentialGroup()
                .addComponent(lblmoving, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        padd.setBackground(new java.awt.Color(0, 95, 79));
        padd.setPreferredSize(new java.awt.Dimension(347, 68));

        lbladd.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lbladd.setForeground(new java.awt.Color(255, 255, 255));
        lbladd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladd.setText("Adding");
        lbladd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbladdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbladdMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paddLayout = new javax.swing.GroupLayout(padd);
        padd.setLayout(paddLayout);
        paddLayout.setHorizontalGroup(
            paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbladd, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
        paddLayout.setVerticalGroup(
            paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paddLayout.createSequentialGroup()
                .addComponent(lbladd, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pset.setBackground(new java.awt.Color(0, 95, 79));
        pset.setPreferredSize(new java.awt.Dimension(347, 68));

        lblset.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblset.setForeground(new java.awt.Color(255, 255, 255));
        lblset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblset.setText("Settings");
        lblset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout psetLayout = new javax.swing.GroupLayout(pset);
        pset.setLayout(psetLayout);
        psetLayout.setHorizontalGroup(
            psetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblset, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
        psetLayout.setVerticalGroup(
            psetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psetLayout.createSequentialGroup()
                .addComponent(lblset, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        plogout.setBackground(new java.awt.Color(0, 95, 79));
        plogout.setPreferredSize(new java.awt.Dimension(347, 68));

        lbllogout.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(255, 255, 255));
        lbllogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogout.setText("Log out");
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout plogoutLayout = new javax.swing.GroupLayout(plogout);
        plogout.setLayout(plogoutLayout);
        plogoutLayout.setHorizontalGroup(
            plogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbllogout, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
        plogoutLayout.setVerticalGroup(
            plogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plogoutLayout.createSequentialGroup()
                .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblicon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw2/t1/warehouse_64px.png"))); // NOI18N

        lblback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw2/t1/back_48px.png"))); // NOI18N
        lblback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblbackMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pdash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pmoving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(padd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lblicon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblwms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblback)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblwms, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblicon1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pdash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pmoving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(padd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(plogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pchange.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pchangeLayout = new javax.swing.GroupLayout(pchange);
        pchange.setLayout(pchangeLayout);
        pchangeLayout.setHorizontalGroup(
            pchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        pchangeLayout.setVerticalGroup(
            pchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(pchange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pchange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1043, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void getkey(){        
        try {
            
            String url = AppConfig.dbUrl();
            String uname = AppConfig.dbUser();
            String pass = AppConfig.dbPassword();
            String query = "SELECT * FROM registration WHERE name = '"+SorL.username+"'";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, uname, pass);
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);

            if(rs.next()){
                keynic = rs.getString("nic");              
            }
           st.close();
           connection.close();         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }      
    }
    
    public void setcolor(JPanel p){
        p.setBackground(new Color (0,130,107));
    }
    
    public void resetcolor(JPanel p){
        p.setBackground(new Color (0,95,79));
    }
    
    private void lbldashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldashMouseEntered
        // TODO add your handling code here:
        setcolor(pdash);
    }//GEN-LAST:event_lbldashMouseEntered

    private void lbldashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldashMouseExited
        // TODO add your handling code here:
        resetcolor(pdash);
    }//GEN-LAST:event_lbldashMouseExited

    private void lblmovingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmovingMouseEntered
        // TODO add your handling code here:
        setcolor(pmoving);
    }//GEN-LAST:event_lblmovingMouseEntered

    private void lblmovingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmovingMouseExited
        // TODO add your handling code here:
        resetcolor(pmoving);
    }//GEN-LAST:event_lblmovingMouseExited

    private void lbladdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladdMouseEntered
        // TODO add your handling code here:
        setcolor(padd);
    }//GEN-LAST:event_lbladdMouseEntered

    private void lbladdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladdMouseExited
        // TODO add your handling code here:
        resetcolor(padd);
    }//GEN-LAST:event_lbladdMouseExited

    private void lblsetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsetMouseEntered
        // TODO add your handling code here:
        setcolor(pset);
    }//GEN-LAST:event_lblsetMouseEntered

    private void lblsetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsetMouseExited
        // TODO add your handling code here:
        resetcolor(pset);
    }//GEN-LAST:event_lblsetMouseExited

    private void lbllogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseEntered
        // TODO add your handling code here:
        setcolor(plogout);
    }//GEN-LAST:event_lbllogoutMouseEntered

    private void lbllogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseExited
        // TODO add your handling code here:
        resetcolor(plogout);
    }//GEN-LAST:event_lbllogoutMouseExited

    private void lbldashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldashMouseClicked
        // TODO add your handling code here:
        dashboard dash = new dashboard();
        pchange.removeAll();
        pchange.add(dash).setVisible(true);
        dash.getContentPane().setBackground( Color.WHITE );
    }//GEN-LAST:event_lbldashMouseClicked

    private void lblsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsetMouseClicked
        // TODO add your handling code here:
        settings set = new settings();
        pchange.removeAll();
        pchange.add(set).setVisible(true);
        set.getContentPane().setBackground( Color.WHITE );
    }//GEN-LAST:event_lblsetMouseClicked

    private void lbllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseClicked
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(this, "Are you sure?","Log out", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(r==JOptionPane.YES_OPTION){
            new SorL().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_lbllogoutMouseClicked

    private void lblmovingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmovingMouseClicked
        // TODO add your handling code here:
        moving move = new moving();
        pchange.removeAll();
        pchange.add(move).setVisible(true);
        move.getContentPane().setBackground( Color.WHITE );
    }//GEN-LAST:event_lblmovingMouseClicked

    private void lbladdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladdMouseClicked
        // TODO add your handling code here:
        adding add = new adding();
        pchange.removeAll();
        pchange.add(add).setVisible(true);
        add.getContentPane().setBackground( Color.WHITE );
    }//GEN-LAST:event_lbladdMouseClicked

    private void lblbackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseReleased
        // TODO add your handling code here:
        new SorL().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblbackMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbladd;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lbldash;
    private javax.swing.JLabel lblicon1;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblmoving;
    private javax.swing.JLabel lblset;
    private javax.swing.JLabel lblwms;
    private javax.swing.JPanel padd;
    private javax.swing.JPanel pchange;
    private javax.swing.JPanel pdash;
    private javax.swing.JPanel plogout;
    private javax.swing.JPanel pmoving;
    private javax.swing.JPanel pset;
    // End of variables declaration//GEN-END:variables
}
