/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cw2.t1;

import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class moving extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashboard
     */
    public moving() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblstock = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnview1 = new javax.swing.JButton();
        btnclear1 = new javax.swing.JButton();
        lbloptions = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblloction = new javax.swing.JLabel();
        cblocation = new javax.swing.JComboBox<>();
        lbltrans = new javax.swing.JLabel();
        cbtrans = new javax.swing.JComboBox<>();
        btnsend = new javax.swing.JButton();
        btnview2 = new javax.swing.JButton();
        btnclear2 = new javax.swing.JButton();
        lblcrates = new javax.swing.JLabel();
        txtl = new javax.swing.JTextField();
        txtm = new javax.swing.JTextField();
        txts = new javax.swing.JTextField();
        lbll = new javax.swing.JLabel();
        lblm = new javax.swing.JLabel();
        lbls = new javax.swing.JLabel();
        lblsl = new javax.swing.JLabel();
        lblsm = new javax.swing.JLabel();
        lblss = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(673, 572));

        lblstock.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblstock.setForeground(new java.awt.Color(0, 0, 0));
        lblstock.setText("Your current stock : ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Package", "Crates L", "Crates M", "Crates S", "Duration", "NIC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnview1.setBackground(new java.awt.Color(0, 95, 79));
        btnview1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnview1.setText("View");
        btnview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnview1ActionPerformed(evt);
            }
        });

        btnclear1.setBackground(new java.awt.Color(0, 95, 79));
        btnclear1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnclear1.setText("Clear");
        btnclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear1ActionPerformed(evt);
            }
        });

        lbloptions.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lbloptions.setForeground(new java.awt.Color(0, 0, 0));
        lbloptions.setText("Available options : ");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Warehouse Id", "Address", "Distance (km)", "Time (h)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        lblloction.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lblloction.setForeground(new java.awt.Color(0, 0, 0));
        lblloction.setText("Branch :");

        cblocation.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        cblocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Kandy", "Matara", "Colombo", "Jaffna" }));

        lbltrans.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lbltrans.setForeground(new java.awt.Color(0, 0, 0));
        lbltrans.setText("Transport method :");

        cbtrans.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        cbtrans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Van", "Truck" }));

        btnsend.setBackground(new java.awt.Color(0, 95, 79));
        btnsend.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        btnview2.setBackground(new java.awt.Color(0, 95, 79));
        btnview2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnview2.setText("View");
        btnview2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnview2ActionPerformed(evt);
            }
        });

        btnclear2.setBackground(new java.awt.Color(0, 95, 79));
        btnclear2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnclear2.setText("Clear");
        btnclear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear2ActionPerformed(evt);
            }
        });

        lblcrates.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lblcrates.setForeground(new java.awt.Color(0, 0, 0));
        lblcrates.setText("No of crates :");

        txtl.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        txtl.setForeground(new java.awt.Color(0, 0, 0));
        txtl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlKeyReleased(evt);
            }
        });

        txtm.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        txtm.setForeground(new java.awt.Color(0, 0, 0));
        txtm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmKeyReleased(evt);
            }
        });

        txts.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        txts.setForeground(new java.awt.Color(0, 0, 0));
        txts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsKeyReleased(evt);
            }
        });

        lbll.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lbll.setForeground(new java.awt.Color(0, 0, 0));
        lbll.setText("L");

        lblm.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lblm.setForeground(new java.awt.Color(0, 0, 0));
        lblm.setText("M");

        lbls.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lbls.setForeground(new java.awt.Color(0, 0, 0));
        lbls.setText("S");

        lblsl.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lblsl.setForeground(new java.awt.Color(204, 0, 0));

        lblsm.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lblsm.setForeground(new java.awt.Color(204, 0, 0));

        lblss.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        lblss.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsend)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblstock)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnclear1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnview1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbloptions)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnclear2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnview2))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblloction)
                                .addComponent(lbltrans)
                                .addComponent(lblcrates))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbll)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(lblsl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblm)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(lblsm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbls)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(lblss, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cblocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbtrans, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstock)
                    .addComponent(btnview1)
                    .addComponent(btnclear1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbloptions)
                    .addComponent(btnview2)
                    .addComponent(btnclear2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblloction)
                    .addComponent(cblocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltrans))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblcrates)
                        .addComponent(txtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbll)
                        .addComponent(lblm)
                        .addComponent(lbls))
                    .addComponent(lblsm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblss, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnsend)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnview1ActionPerformed
        // TODO add your handling code here:
        try{
            String url = AppConfig.dbUrl();
            String uname = AppConfig.dbUser();
            String pass = AppConfig.dbPassword();
            String query = "SELECT * FROM warehouse_req WHERE nic = '"+Interface1.keynic+"'";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, uname, pass);
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);

            if(rs.next()){
                String pa = rs.getString("package");
                String  l = String.valueOf(rs.getInt("crates_l"));
                String  m = String.valueOf(rs.getInt("crates_m"));
                String  s = String.valueOf(rs.getInt("crates_s")); 
                String duration = rs.getString("duration");
                String nic = rs.getString("nic");
                
                String tbData[] = {pa,l,m,s,duration,nic};
                DefaultTableModel tbm = (DefaultTableModel)jTable1.getModel();

                for( int t = tbm.getRowCount() - 1; t >= 0; t-- )
                 {
                     tbm.removeRow(t);
                 }                
                
                tbm.addRow(tbData);
            }
           st.close();
           connection.close();        
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnview1ActionPerformed

    private void btnclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbm = (DefaultTableModel)jTable1.getModel();
        for( int r = tbm.getRowCount() - 1; r>= 0; r-- )
                 {
                     tbm.removeRow(r);
                 }
    }//GEN-LAST:event_btnclear1ActionPerformed

    private void btnview2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnview2ActionPerformed
        // TODO add your handling code here:
        try {
            String url = AppConfig.dbUrl();
            String uname = AppConfig.dbUser();
            String pass = AppConfig.dbPassword();
            String query = "SELECT * FROM other_branches" ;
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, uname, pass);
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);

            while(rs.next()){
                String wid = rs.getString("warehouse_id");
                String address = rs.getString("address");
                String distance = String.valueOf(rs.getInt("distance"));
                String time = String.valueOf(rs.getInt("time"));
                
                String tbData[] = {wid,address,distance,time};
                DefaultTableModel tbm = (DefaultTableModel)jTable2.getModel();  
                tbm.addRow(tbData);
            }
           st.close();
           connection.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnview2ActionPerformed

    public static void updatedb(){
        try{
        String url = AppConfig.dbUrl();
        String uname = AppConfig.dbUser();
        String pass = AppConfig.dbPassword();
        String query = "UPDATE warehouse_req SET crates_l = '"+fl+"', crates_m = '"+fm+"', crates_s = '"+fs+"'";

        Class.forName("com.mysql.jdbc.Driver");
        Connection connection = DriverManager.getConnection(url, uname, pass);
        Statement st = connection.createStatement();
        
        st.executeUpdate(query);
        
        st.close();
        connection.close();
        }
        catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
        }
        }
    
    
    private void btnclear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbm = (DefaultTableModel)jTable2.getModel();
        for( int r = tbm.getRowCount() - 1; r>= 0; r-- )
                 {
                     tbm.removeRow(r);
                 }
    }//GEN-LAST:event_btnclear2ActionPerformed
        int o =1 , bl , bm , bs ;           //b means 'before' ¯\_( ͡° ͜ʖ ͡°)_/¯
        static int fl , fm , fs ;           //f means 'final' ¯\_( ͡° ͜ʖ ͡°)_/¯

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        
        try {
            String url = AppConfig.dbUrl();
            String uname = AppConfig.dbUser();
            String pass = AppConfig.dbPassword();
            String query1 = "SELECT * FROM moving WHERE nic = '"+Interface1.keynic+"'";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, uname, pass);
            Statement st = connection.createStatement();
            ResultSet rs1 = st.executeQuery(query1);

            if(rs1.next()){
                JOptionPane.showMessageDialog(null,"You've already send a request");
                o=0;
            }
           st.close();
           connection.close();
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        if (o==1) {
            if (cblocation.getSelectedItem()=="- Select -" || cbtrans.getSelectedItem()=="- Select -" || lblsl.getText()=="*" || lblsm.getText()=="*" ||lblss.getText()=="*" || txtl.getText().equals("")|| txtm.getText().equals("") || txts.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Please enter requested details");
        }
        else{
                try {
            String url = AppConfig.dbUrl();
            String uname = AppConfig.dbUser();
            String pass = AppConfig.dbPassword();
            String query = "SELECT * FROM warehouse_req WHERE nic = '"+Interface1.keynic+"'";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, uname, pass);
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);

            if(rs.next()){
                bl = rs.getInt("crates_l");
                bm = rs.getInt("crates_m");
                bs = rs.getInt("crates_s"); 
            }
           st.close();
           connection.close();
           
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                
            int ml = Integer.parseInt(txtl.getText());     //m means 'moving' ¯\_( ͡° ͜ʖ ͡°)_/¯
            int mm = Integer.parseInt(txtm.getText());
            int ms = Integer.parseInt(txts.getText());
                    
            if(ml<=bl && mm<=bm && ms<=bs){
                String address=null;
                String trans = cbtrans.getSelectedItem().toString();
                
                if (cblocation.getSelectedItem()=="Kandy") {
                    address = "W1";   
                }
                else if(cblocation.getSelectedItem()=="Matara"){
                    address = "W2";
                }
                else if(cblocation.getSelectedItem()=="Colombo"){
                    address = "W3";
                }
                else if(cblocation.getSelectedItem()=="Jaffna"){
                    address = "W4";  
                }
               
                try {
                    String url = AppConfig.dbUrl();
                    String uname = AppConfig.dbUser();
                    String pass = AppConfig.dbPassword();
                    String query = "insert into moving values('"+address+"','"+Interface1.keynic+"','"+trans+"','"+ml+"','"+mm+"',"+ms+")";
                    Class.forName("com.mysql.jdbc.Driver");    
                    Connection connection = DriverManager.getConnection(url, uname, pass);
                    Statement st = connection.createStatement();
                    st.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Your request has been finalized");
                    st.close();
                    connection.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                fl = bl - ml ;
                fm = bm - mm ;
                fs = bs - ms ;
                updatedb();
            }
            else{
                JOptionPane.showMessageDialog(null, "Enter valid no of crates");
            }
        }
        }
        
    }//GEN-LAST:event_btnsendActionPerformed

    private void txtlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlKeyReleased
        // TODO add your handling code here:
        try {
        String PATTERN = "^[0-9]{0,3}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtl.getText());
        
        if(!match.matches()){
            lblsl.setText("*");
        }
        else{
            lblsl.setText(null);
        }           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtlKeyReleased

    private void txtmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmKeyReleased
        // TODO add your handling code here:
        try {
        String PATTERN = "^[0-9]{0,3}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtm.getText());
        
        if(!match.matches()){
            lblsm.setText("*");
        }
        else{
            lblsm.setText(null);
        }           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtmKeyReleased

    private void txtsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsKeyReleased
        // TODO add your handling code here:
        try {
        String PATTERN = "^[0-9]{0,3}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txts.getText());
        
        if(!match.matches()){
            lblss.setText("*");
        }
        else{
            lblss.setText(null);
        }           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtsKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear1;
    private javax.swing.JButton btnclear2;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton btnview1;
    private javax.swing.JButton btnview2;
    private javax.swing.JComboBox<String> cblocation;
    private javax.swing.JComboBox<String> cbtrans;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblcrates;
    private javax.swing.JLabel lbll;
    private javax.swing.JLabel lblloction;
    private javax.swing.JLabel lblm;
    private javax.swing.JLabel lbloptions;
    private javax.swing.JLabel lbls;
    private javax.swing.JLabel lblsl;
    private javax.swing.JLabel lblsm;
    private javax.swing.JLabel lblss;
    private javax.swing.JLabel lblstock;
    private javax.swing.JLabel lbltrans;
    private javax.swing.JTextField txtl;
    private javax.swing.JTextField txtm;
    private javax.swing.JTextField txts;
    // End of variables declaration//GEN-END:variables
}
