/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cw2.t1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Properties;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class passrec extends javax.swing.JFrame {

    public static int r;
    public static String newpass,conpass;
    
    public passrec() throws MessagingException {
        initComponents();
        pnewpass.setVisible(false);
        r = ThreadLocalRandom.current().nextInt(100000, 1000000);
        SendMail(SorL.em);
        System.out.println("Sent");
    }
    
    private static Message PrepareMessage(Session session, String myemail, String recepient) {
        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(myemail));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(recepient));
            message.setSubject("WMS Verification Code");
            message.setText("Hey there, \n Your verification code : " + r);
            return message;
        } catch (MessagingException ex) {
            Logger.getLogger(MailVerification.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public static void SendMail(String recepient) throws MessagingException{
        Properties properties = new Properties();
        
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");
        
        String myemail = AppConfig.smtpUser();
        String mypassword = AppConfig.smtpPassword();
        
        Session session = Session.getDefaultInstance(properties, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(myemail, mypassword);
            }           
});
        Message message = PrepareMessage(session,myemail,recepient);
        Transport.send(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblback = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblwms = new javax.swing.JLabel();
        lblwms1 = new javax.swing.JLabel();
        lblwms2 = new javax.swing.JLabel();
        pnewpass = new javax.swing.JPanel();
        lblnewpass = new javax.swing.JLabel();
        lblconpass = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        txtnewpass = new javax.swing.JTextField();
        txtconpass = new javax.swing.JTextField();
        pvc = new javax.swing.JPanel();
        lblvalid = new javax.swing.JLabel();
        lblvalid1 = new javax.swing.JLabel();
        txtvc = new javax.swing.JTextField();
        lblvc = new javax.swing.JLabel();
        btnconfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Warehouse Management System");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 95, 79));

        lblback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw2/t1/back_48px.png"))); // NOI18N
        lblback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblbackMouseReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw2/t1/warehouse_64px.png"))); // NOI18N

        lblwms.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblwms.setForeground(new java.awt.Color(255, 255, 255));
        lblwms.setText("Warehouse");

        lblwms1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblwms1.setForeground(new java.awt.Color(255, 255, 255));
        lblwms1.setText("Management");

        lblwms2.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblwms2.setForeground(new java.awt.Color(255, 255, 255));
        lblwms2.setText("System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(lblback, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel1)
                        .addComponent(lblwms)
                        .addComponent(lblwms1)
                        .addComponent(lblwms2))
                    .addContainerGap(74, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblback, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jLabel1)
                    .addGap(49, 49, 49)
                    .addComponent(lblwms, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addComponent(lblwms1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(95, 95, 95)
                    .addComponent(lblwms2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        pnewpass.setBackground(new java.awt.Color(255, 255, 255));

        lblnewpass.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblnewpass.setForeground(new java.awt.Color(0, 0, 0));
        lblnewpass.setText("New password :");

        lblconpass.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblconpass.setForeground(new java.awt.Color(0, 0, 0));
        lblconpass.setText("Confirm new password :");

        btnsave.setBackground(new java.awt.Color(0, 95, 79));
        btnsave.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        txtnewpass.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        txtconpass.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        javax.swing.GroupLayout pnewpassLayout = new javax.swing.GroupLayout(pnewpass);
        pnewpass.setLayout(pnewpassLayout);
        pnewpassLayout.setHorizontalGroup(
            pnewpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnewpassLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnewpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblconpass)
                    .addComponent(lblnewpass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnewpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtconpass, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnewpassLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        pnewpassLayout.setVerticalGroup(
            pnewpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnewpassLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnewpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnewpass)
                    .addComponent(txtnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnewpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblconpass)
                    .addComponent(txtconpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnsave)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pvc.setBackground(new java.awt.Color(255, 255, 255));

        lblvalid.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        lblvalid.setForeground(new java.awt.Color(0, 0, 0));
        lblvalid.setText("We have send a verification code to your email");

        lblvalid1.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        lblvalid1.setForeground(new java.awt.Color(0, 0, 0));
        lblvalid1.setText("Enter the code to continue ...");

        txtvc.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        lblvc.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblvc.setForeground(new java.awt.Color(0, 0, 0));
        lblvc.setText("Verification code :");

        btnconfirm.setBackground(new java.awt.Color(0, 95, 79));
        btnconfirm.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnconfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirm.setText("Confirm");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pvcLayout = new javax.swing.GroupLayout(pvc);
        pvc.setLayout(pvcLayout);
        pvcLayout.setHorizontalGroup(
            pvcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pvcLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblvc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtvc, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pvcLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pvcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pvcLayout.createSequentialGroup()
                        .addGroup(pvcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblvalid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pvcLayout.createSequentialGroup()
                        .addComponent(btnconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))))
        );
        pvcLayout.setVerticalGroup(
            pvcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pvcLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(lblvalid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblvalid1)
                .addGap(51, 51, 51)
                .addGroup(pvcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvc)
                    .addComponent(txtvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnconfirm)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pvc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnewpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnewpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1043, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void updatedb(){
        try{
        String url = AppConfig.dbUrl();
        String uname = AppConfig.dbUser();
        String pass = AppConfig.dbPassword();
        String query = "UPDATE registration SET password = '"+conpass+"' where name = '"+SorL.username+"'";

        Class.forName("com.mysql.jdbc.Driver");
        Connection connection = DriverManager.getConnection(url, uname, pass);
        Statement st = connection.createStatement();
        
        st.executeUpdate(query);
        
        st.close();
        connection.close();
        }
        catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void lblbackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseReleased
        // TODO add your handling code here:
        new SorL().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblbackMouseReleased

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
        String random = String.valueOf(r);
        String vc = txtvc.getText();
        if(vc.equals(random)){
            JOptionPane.showMessageDialog(null,"Please enter a new password");
            pnewpass.setVisible(true);
            pvc.setVisible(false);          
        }
        else{
        JOptionPane.showMessageDialog(null,"Please enter the valid verification code");
        }
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        conpass = txtconpass.getText();
        newpass = txtnewpass.getText();
        if(conpass.equals(newpass)){
            updatedb();
            JOptionPane.showMessageDialog(null,"Your password has been updated");
            new SorL().setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"New password & confirm password doesn't match");
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(passrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(passrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(passrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new passrec().setVisible(true);
                } catch (MessagingException ex) {
                    Logger.getLogger(passrec.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconfirm;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lblconpass;
    private javax.swing.JLabel lblnewpass;
    private javax.swing.JLabel lblvalid;
    private javax.swing.JLabel lblvalid1;
    private javax.swing.JLabel lblvc;
    private javax.swing.JLabel lblwms;
    private javax.swing.JLabel lblwms1;
    private javax.swing.JLabel lblwms2;
    private javax.swing.JPanel pnewpass;
    private javax.swing.JPanel pvc;
    private javax.swing.JTextField txtconpass;
    private javax.swing.JTextField txtnewpass;
    private javax.swing.JTextField txtvc;
    // End of variables declaration//GEN-END:variables
}
