/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cw2.t1;

import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class settings extends javax.swing.JInternalFrame {

    
    public static String iname;
    public static String icity;
    public static String ipassword;
    public static String icn;
    
    /**
     * Creates new form dashboard
     */
    public settings() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpro = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        lblcn = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        txtcn = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnview = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnclear = new javax.swing.JButton();
        lblsname = new javax.swing.JLabel();
        lblscity = new javax.swing.JLabel();
        lblspassword = new javax.swing.JLabel();
        lblscn = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        lblpro1 = new javax.swing.JLabel();
        lblname1 = new javax.swing.JLabel();
        lblcity1 = new javax.swing.JLabel();
        lblpass1 = new javax.swing.JLabel();
        lblcn1 = new javax.swing.JLabel();
        txtname1 = new javax.swing.JTextField();
        txtcity1 = new javax.swing.JTextField();
        txtpass1 = new javax.swing.JTextField();
        txtcn1 = new javax.swing.JTextField();
        btnsave1 = new javax.swing.JButton();
        btnview1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnclear1 = new javax.swing.JButton();
        lblsname1 = new javax.swing.JLabel();
        lblscity1 = new javax.swing.JLabel();
        lblspassword1 = new javax.swing.JLabel();
        lblscn1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(673, 572));

        lblpro.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblpro.setForeground(new java.awt.Color(0, 0, 0));
        lblpro.setText("My profile : ");

        lblname.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblname.setForeground(new java.awt.Color(0, 0, 0));
        lblname.setText("Name : ");

        lblcity.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblcity.setForeground(new java.awt.Color(0, 0, 0));
        lblcity.setText("City : ");

        lblpass.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblpass.setForeground(new java.awt.Color(0, 0, 0));
        lblpass.setText("Password : ");

        lblcn.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblcn.setForeground(new java.awt.Color(0, 0, 0));
        lblcn.setText("Contact Num : ");

        txtname.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });

        txtcity.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcityKeyReleased(evt);
            }
        });

        txtpass.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassKeyReleased(evt);
            }
        });

        txtcn.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtcn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcnKeyReleased(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(0, 95, 79));
        btnsave.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnview.setBackground(new java.awt.Color(0, 95, 79));
        btnview.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "NIC", "City", "Email", "Password", "Contact Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnclear.setBackground(new java.awt.Color(0, 95, 79));
        btnclear.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        lblsname.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblsname.setForeground(new java.awt.Color(204, 0, 0));

        lblscity.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblscity.setForeground(new java.awt.Color(204, 0, 0));

        lblspassword.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblspassword.setForeground(new java.awt.Color(204, 0, 0));

        lblscn.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblscn.setForeground(new java.awt.Color(204, 0, 0));

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(673, 572));

        lblpro1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblpro1.setForeground(new java.awt.Color(0, 0, 0));
        lblpro1.setText("My profile : ");

        lblname1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblname1.setForeground(new java.awt.Color(0, 0, 0));
        lblname1.setText("Name : ");

        lblcity1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblcity1.setForeground(new java.awt.Color(0, 0, 0));
        lblcity1.setText("City : ");

        lblpass1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblpass1.setForeground(new java.awt.Color(0, 0, 0));
        lblpass1.setText("Password : ");

        lblcn1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblcn1.setForeground(new java.awt.Color(0, 0, 0));
        lblcn1.setText("Contact Num : ");

        txtname1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtname1KeyReleased(evt);
            }
        });

        txtcity1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtcity1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcity1KeyReleased(evt);
            }
        });

        txtpass1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtpass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpass1KeyReleased(evt);
            }
        });

        txtcn1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtcn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcn1KeyReleased(evt);
            }
        });

        btnsave1.setBackground(new java.awt.Color(0, 95, 79));
        btnsave1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnsave1.setText("Save");
        btnsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave1ActionPerformed(evt);
            }
        });

        btnview1.setBackground(new java.awt.Color(0, 95, 79));
        btnview1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnview1.setText("View");
        btnview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnview1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "NIC", "City", "Email", "Password", "Contact Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnclear1.setBackground(new java.awt.Color(0, 95, 79));
        btnclear1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnclear1.setText("Clear");
        btnclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear1ActionPerformed(evt);
            }
        });

        lblsname1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblsname1.setForeground(new java.awt.Color(204, 0, 0));

        lblscity1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblscity1.setForeground(new java.awt.Color(204, 0, 0));

        lblspassword1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblspassword1.setForeground(new java.awt.Color(204, 0, 0));

        lblscn1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblscn1.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblname1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblcity1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblpass1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblcn1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtname1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(txtcity1)
                                    .addComponent(txtpass1)
                                    .addComponent(txtcn1)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblpro1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                .addComponent(btnclear1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnview1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsave1)
                                .addGap(7, 7, 7)))
                        .addGap(2, 2, 2)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblsname1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblscity1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblspassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblscn1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpro1)
                    .addComponent(btnsave1)
                    .addComponent(btnview1)
                    .addComponent(btnclear1))
                .addGap(30, 30, 30)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblname1)
                                            .addComponent(txtname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblsname1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtcity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblcity1)))
                                    .addComponent(lblscity1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpass1)))
                            .addComponent(lblspassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcn1)))
                    .addComponent(lblscn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblcity, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblpass, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblcn, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(txtcity)
                                    .addComponent(txtpass)
                                    .addComponent(txtcn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblpro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                .addComponent(btnclear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnview)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsave)
                                .addGap(7, 7, 7)))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblsname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblscity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblspassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblscn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpro)
                    .addComponent(btnsave)
                    .addComponent(btnview)
                    .addComponent(btnclear))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblname)
                                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblsname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblcity)))
                                    .addComponent(lblscity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpass)))
                            .addComponent(lblspassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcn)))
                    .addComponent(lblscn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:         
        try{
            String url = AppConfig.dbUrl();
            String uname = AppConfig.dbUser();
            String pass = AppConfig.dbPassword();
            String query = "SELECT * FROM registration WHERE nic = '"+Interface1.keynic+"'";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, uname, pass);
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);

            if(rs.next()){
                String name = rs.getString("name");
                String nic = rs.getString("nic");
                String city = rs.getString("city");
                String email = rs.getString("email");  
                String password = rs.getString("password");
                String cn = String.valueOf(rs.getInt("contact_num"));
                
                String tbData[] = {name,nic,city,email,password,cn};
                DefaultTableModel tbm = (DefaultTableModel)jTable1.getModel();

                for( int r = tbm.getRowCount() - 1; r >= 0; r-- )
                 {
                     tbm.removeRow(r);
                 }                
                
                tbm.addRow(tbData);
            }
           st.close();
           connection.close();
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnviewActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbm = (DefaultTableModel)jTable1.getModel();
        for( int t = tbm.getRowCount() - 1; t>= 0; t-- )
                 {
                     tbm.removeRow(t);
                 }
    }//GEN-LAST:event_btnclearActionPerformed

    public static int i=1;
    public static int c=1;
    
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        iname = txtname.getText();
        icity = txtcity.getText();
        ipassword = txtpass.getText();
        icn = txtcn.getText();
        
        if(iname.equals("") || icity.equals("") || ipassword.equals("") || icn.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter requested details");
            i=0;
        }  
        if(lblsname.getText()=="*" || lblscity.getText()=="*" || lblspassword.getText()=="*" || lblscn.getText()=="*"){
            JOptionPane.showMessageDialog(null,"Please enter valid details");
            i=0;
        }      
        if(icn.length()==10){} 
        else{JOptionPane.showMessageDialog(null,"Please enter a valid contact number");i=0;}
        if(i==1){
            checkdb();
            if(c==1){
            db();
            JOptionPane.showMessageDialog(null,"Profile updated successfully!");
        }
        }
        
    }//GEN-LAST:event_btnsaveActionPerformed

    public static void checkdb(){
        try{
            String url = AppConfig.dbUrl();
            String uname = AppConfig.dbUser();
            String pass = AppConfig.dbPassword();
            String query = "SELECT * FROM registration WHERE nic = '"+Interface1.keynic+"'";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, uname, pass);
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);

            if(rs.next()){
                String getname = rs.getString("name");
                String getcity = rs.getString("city");  
                String getpassword = rs.getString("password");
                String getcn = String.valueOf(rs.getInt("contact_num"));
                
                if(iname.equals(getname) || icity.equals(getcity) || ipassword.equals(getpassword) || icn.equals(getcn)){
                    JOptionPane.showMessageDialog(null,"Data you entered already exists");
                    c=0;
                }
            }
           st.close();
           connection.close();
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
     
    public static void db(){
        try{
        String url = AppConfig.dbUrl();
        String uname = AppConfig.dbUser();
        String pass = AppConfig.dbPassword();
        String query = "UPDATE registration SET name = '"+iname+"', city = '"+icity+"', password = '"+ipassword+"', contact_num = '"+icn+"' WHERE nic = '"+Interface1.keynic+"' ";

        Class.forName("com.mysql.jdbc.Driver");
        Connection connection = DriverManager.getConnection(url, uname, pass);
        Statement st = connection.createStatement();
        
        st.executeUpdate(query);
        
        st.close();
        connection.close();
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e);}
    }
    
    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        try {      
        String PATTERN = "^[a-zA-Z]{0,30}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtname.getText());
        
        if(!match.matches()){
            lblsname.setText("*");
        }
        else{
            lblsname.setText(null);
        }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtcityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcityKeyReleased
        // TODO add your handling code here:
        try {      
        String PATTERN = "^[a-zA-Z]{0,30}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtcity.getText());
        
        if(!match.matches()){
            lblscity.setText("*");
        }
        else{
            lblscity.setText(null);
        }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtcityKeyReleased

    private void txtpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyReleased
        // TODO add your handling code here:
        try {
        String PATTERN = "^[a-zA-Z0-9]{0,30}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtpass.getText());
        
        if(!match.matches()){
            lblspassword.setText("*");
        }
        else{
            lblspassword.setText(null);
        }           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtpassKeyReleased

    private void txtcnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnKeyReleased
        // TODO add your handling code here:
        try {
        String PATTERN = "^[0-9]{0,10}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtcn.getText());
        
        if(!match.matches()){
            lblscn.setText("*");
        }
        else{
            lblscn.setText(null);
        }           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txtcnKeyReleased

    private void txtname1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtname1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtname1KeyReleased

    private void txtcity1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcity1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcity1KeyReleased

    private void txtpass1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpass1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpass1KeyReleased

    private void txtcn1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcn1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcn1KeyReleased

    private void btnsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsave1ActionPerformed

    private void btnview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnview1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnview1ActionPerformed

    private void btnclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclear1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclear1;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsave1;
    private javax.swing.JButton btnview;
    private javax.swing.JButton btnview1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblcity1;
    private javax.swing.JLabel lblcn;
    private javax.swing.JLabel lblcn1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblname1;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblpass1;
    private javax.swing.JLabel lblpro;
    private javax.swing.JLabel lblpro1;
    private javax.swing.JLabel lblscity;
    private javax.swing.JLabel lblscity1;
    private javax.swing.JLabel lblscn;
    private javax.swing.JLabel lblscn1;
    private javax.swing.JLabel lblsname;
    private javax.swing.JLabel lblsname1;
    private javax.swing.JLabel lblspassword;
    private javax.swing.JLabel lblspassword1;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcity1;
    private javax.swing.JTextField txtcn;
    private javax.swing.JTextField txtcn1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtpass1;
    // End of variables declaration//GEN-END:variables
}
