/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cw2.t1;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;

/**
 *
 * @author PMSU
 */
public class SorL extends javax.swing.JFrame {

    public static int i = 0;
    
    /**
     * Creates new form SorL
     */
    public SorL() {
        initComponents();
    }

    public static String username;
    public static String password;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        btnforgetpassword = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        btnregister = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblwms = new javax.swing.JLabel();
        lblwms1 = new javax.swing.JLabel();
        lblwms2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Warehouse Management System");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblusername.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblusername.setForeground(new java.awt.Color(0, 0, 0));
        lblusername.setText("User Name :");

        lblpassword.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(0, 0, 0));
        lblpassword.setText("Password :");

        txtusername.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        txtpassword.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        btnforgetpassword.setBackground(new java.awt.Color(50, 95, 87));
        btnforgetpassword.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnforgetpassword.setForeground(new java.awt.Color(255, 255, 255));
        btnforgetpassword.setText("Forget Password");
        btnforgetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforgetpasswordActionPerformed(evt);
            }
        });

        btnlogin.setBackground(new java.awt.Color(0, 95, 79));
        btnlogin.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Log In");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        btnregister.setBackground(new java.awt.Color(0, 95, 79));
        btnregister.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnregister.setForeground(new java.awt.Color(255, 255, 255));
        btnregister.setText("Register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 95, 79));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cw2/t1/warehouse_64px.png"))); // NOI18N

        lblwms.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblwms.setForeground(new java.awt.Color(255, 255, 255));
        lblwms.setText("Warehouse");

        lblwms1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblwms1.setForeground(new java.awt.Color(255, 255, 255));
        lblwms1.setText("Management");

        lblwms2.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblwms2.setForeground(new java.awt.Color(255, 255, 255));
        lblwms2.setText("System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel1)
                        .addComponent(lblwms)
                        .addComponent(lblwms1)
                        .addComponent(lblwms2))
                    .addContainerGap(74, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jLabel1)
                    .addGap(49, 49, 49)
                    .addComponent(lblwms, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addComponent(lblwms1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(95, 95, 95)
                    .addComponent(lblwms2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblusername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblpassword, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(txtpassword))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnregister, javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnforgetpassword)
                                .addGap(18, 18, 18)
                                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(121, 121, 121))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusername)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnforgetpassword)
                    .addComponent(btnlogin))
                .addGap(18, 18, 18)
                .addComponent(btnregister)
                .addGap(121, 121, 121))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1043, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        new SignIn().setVisible(true);
        this.setVisible(false);
        //this.dispose();
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        username = txtusername.getText();
        password = txtpassword.getText();
        if(username.equals("") || password.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter requested details");
        }
        else{
            db();
            if(i==1){               
            new Interface1().setVisible(true);
            this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnloginActionPerformed

    public static String un,em;
    static int w = 1;
    
    private void btnforgetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforgetpasswordActionPerformed
        // TODO add your handling code here:
        un = txtusername.getText();
        
        if(un.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter your username");
        }
        else{
            
            try {
                String url = AppConfig.dbUrl();
                String uname = AppConfig.dbUser();
                String pass = AppConfig.dbPassword();
                String query1 = "SELECT * FROM registration WHERE name = '"+username+"'";
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection connection = DriverManager.getConnection(url, uname, pass);
                Statement st = connection.createStatement();
                ResultSet rs1 = st.executeQuery(query1);
                
                if(rs1.next()){
                    em = JOptionPane.showInputDialog("Enter your Email : ");
                    checkdb();
                    if(w==1){
                        try {
                            new passrec().setVisible(true);
                        } catch (MessagingException ex) {
                            Logger.getLogger(SorL.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        this.setVisible(false);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Your username is incorrect");
                }
                
                st.close();
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(SorL.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SorL.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnforgetpasswordActionPerformed

    public static void checkdb(){
        try { w=1;
            String url = AppConfig.dbUrl();
            String uname = AppConfig.dbUser();
            String pass = AppConfig.dbPassword();
            String query1 = "SELECT * FROM registration WHERE name = '"+un+"' and email = '"+em+"'";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, uname, pass);
            Statement st = connection.createStatement();
            ResultSet rs1 = st.executeQuery(query1);

            if(rs1.next()){
                JOptionPane.showMessageDialog(null,"We've send a verification code");               
            }
            else{
                JOptionPane.showMessageDialog(null,"Your email is incorrect");
                w=0;
           }
           st.close();
           connection.close();
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public static void db(){
              
        try {
            int n=0,p=0 ;
            String url = AppConfig.dbUrl();
            String uname = AppConfig.dbUser();
            String pass = AppConfig.dbPassword();
            String query1 = "SELECT * FROM registration WHERE name = '"+username+"' and password = '"+password+"'";
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, uname, pass);
            Statement st = connection.createStatement();
            ResultSet rs1 = st.executeQuery(query1);

            if(rs1.next()){
                JOptionPane.showMessageDialog(null,"Login successfully!");
                i=1;
            }
            else{
                JOptionPane.showMessageDialog(null,"Either your username or password is incorrect");
           }
           st.close();
           connection.close();
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SorL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SorL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SorL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SorL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SorL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnforgetpassword;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JLabel lblwms;
    private javax.swing.JLabel lblwms1;
    private javax.swing.JLabel lblwms2;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
